#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

source=$("$adr_bin_dir/_adr_file" "${1:?SOURCE}")
source_dir=${source%/*}
source_filename=${source##*/}
target=${2:?TARGET}
target_num=$(printf "%04d" ${target})
target_filename=${source_filename/[0-9][0-9][0-9][0-9]/${target_num}}

source_title=$("$adr_bin_dir/_adr_title" "$source")
source_short_title=$(echo "${source_title}" | sed 's/^[0-9]\+//g')
# source_num=$(echo "${source_title}" | sed 's/\(^[0-9]\+\)\..*/\1/g')
target_title="${target}${source_short_title}"

pattern_escape_cmd='sed -e s/[]\/$*.^[]/\\&/g'
sub_escape_cmd='sed -e s/[\/&]/\\&/g'
source_filename_escaped=$(echo "${source_filename}" | ${pattern_escape_cmd})
target_filename_escaped=$(echo "${target_filename}" | ${sub_escape_cmd})

source_title_escaped=$(echo "${source_title}" | ${pattern_escape_cmd})
target_title_escaped=$(echo "${target_title}" | ${sub_escape_cmd})

# update file
mv ${source} ${source_dir}/${target_filename}

# update references (it will update $target_file as well)
for adr_filename in $("$adr_bin_dir/adr-list")
do
	sed -i "s/${source_filename_escaped}/${target_filename_escaped}/g ; s/${source_title_escaped}/${target_title_escaped}/g" ${adr_filename}
done 
