#!/bin/bash
set -e

file=$($(dirname $0)/_adr-file "${1:?FILE}")
op=${2:?OP: 'supercedes' or 'superceded-by'}
other=$($(dirname $0)/_adr-file "${3:?OTHER FILE}")

other_link="$(basename "$other")"
other_title="$($(dirname $0)/adr-title "$other")"

awk -v other_link="$other_link" -v other_title="$other_title" -v op="$op" '
BEGIN {
    status_line=0
    status_updated=0
}

/^##/ { 
    status_line=0
}

/^## Status$/ { 
    status_line=1
}
    
/Accepted/ && status_line {
    link="[" other_title "](" other_link ")"

    if (op == "superceded-by") {
       print "Superceded by " link
    } else if (op == "supercedes") {
        print
        print ""
        print "Supercedes " link
    }
    next
}

{ print }

' $file > $file.tmp

mv $file.tmp $file
