#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

file_type="$($adr_bin_dir/_adr_file_type)"

if [ "$file_type" = "md" ]
then
  "$adr_bin_dir/_adr_status" "$1" | sed -n -E 's/^(.+) \[.*\]\(0*([1-9][0-9]*).*\)/\2=\1/p'
else
  "$adr_bin_dir/_adr_status" "$1" | sed -n -E 's/^(.+) link:0*([1-9][0-9]*).*\[.*\]/\2=\1/p'
fi
