#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

args=$(getopt i:o: $*)
set -- $args

for arg
do
    case "$arg"
    in
        -i)
            intro="$2"
            shift 2
            ;;
        -o)
            outro="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
    esac
done

cat <<EOF 
# Architecture Decision Records

EOF

if [ ! -z $intro ]
then
    cat "$intro"
    echo
fi

for f in $("$adr_bin_dir/adr-list")
do
    title=$("$adr_bin_dir/_adr_title" $f)
    link=$(basename $f)

    echo "* [$title]($link)"
done

if [ ! -z $outro ]
then
    echo
    cat "$outro"
fi
