#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

# the current status
"$adr_bin_dir/_adr_status" "$1" | sed -n -E 's/^(.+) \[.*\]\(\{\{< ref "0*([1-9][0-9]*).*" >}}\)/\2=\1/p'

# links
sed -n '/## Links/,//p' $("$adr_bin_dir/_adr_file" "$1") | sed -n -E 's/^\* (.+) \[.*\]\(\{\{< ref "0*([1-9][0-9]*).*" >}}\)/\2=\1/p'
