#!/bin/bash
set -e

bindir="$(dirname $0)"
args=$(getopt i:o: $*)
set -- $args

for arg
do
    case "$arg"
    in
        -i)
            intro="$2"
            shift 2
            ;;
        -o)
            outro="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
    esac
done

cat <<EOF 
# Architecture Decision Records

EOF

if [ ! -z $intro ]
then
    cat "$intro"
    echo
fi

for f in $($bindir/adr-list)
do
    title=$($bindir/_adr_title $f)
    link=$(basename $f)

    echo "* [$title]($link)"
done

if [ ! -z $outro ]
then
    echo
    cat "$outro"
fi
