#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

## usage: adr link SOURCE LINK TARGET REVERSE-LINK
##
## Creates a link between two ADRs, from SOURCE to TARGET new.
## SOURCE and TARGET are both a reference (number or partial filename) to an ADR
## LINK is the description of the link created in the SOURCE.
## REVERSE-LINK is the description of the link created in the TARGET
##
## E.g. to create link ADR 12 to ADR 10
##
##     adr link 12 Amends 10 "Amended by"
##

source="${1:?SOURCE}"
target="${2:?TARGET}"

"$adr_bin_dir/_adr_move" "$source" "$target"
