#!/bin/bash
set -e

args=$(getopt s: $*)
set -- $args

for arg
do
    case "$arg"
    in
        -s)
            superceded="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
    esac
done

template=${ADR_TEMPLATE:-$(dirname $0)/template.md}
dstdir=$($(dirname $0)/_adr_dir)

title="$@"

if [ -z "$title" ]
then
    echo ERROR: no title given
    exit 1
fi

if [ -d $dstdir ]
then
    maxid=$(ls $dstdir | grep -Eo '^[0-9]+' | sort -rn | head -1)
    newnum=$(($maxid + 1))
else
    newnum=1
fi

newid=$(printf "%04d" $newnum)
slug=$(echo -n $title | tr -Ccs [:alnum:] - | tr [:upper:] [:lower:] | sed -e 's/[^[:alnum:]]*$//' -e 's/^[^[:alnum:]]*//')
dstfile=$dstdir/$newid-$slug.md
date=${ADR_DATE:-$(date +%d/%m/%Y)}

if [ ! -z $superceded ]
then
    superceded_file=$($(dirname $0)/_adr_file $superceded)
fi

mkdir -p $dstdir
cat $template | sed \
    -e "s|NUMBER|$newnum|" \
    -e "s|TITLE|$title|" \
    -e "s|DATE|$date|" \
    -e "s|STATUS|Accepted|" \
    > $dstfile

if [ ! -z $superceded ]
then
    superceded_file=$($(dirname $0)/_adr_file "$superceded")
    _adr_update_status $dstfile supercedes $superceded_file
    _adr_update_status $superceded_file superceded-by $dstfile
fi

${VISUAL:-${EDITOR:-true}} $dstfile
echo $dstfile
