#!/bin/bash
set -e
source "$(dirname $0)/config.sh"

## usage: adr init
## 
## Initialises the directory of architecture decision records:
## 
##  * creates a subdirectory of the current working directory named doc/adr
##  * creates the first ADR in that subdirectory, recording the decision to
##    record architectural decisions with ADRs.

VISUAL=true ADR_TEMPLATE="$adr_template_dir/init.md" \
      "$adr_bin_dir/adr-new" record-architecture-decisions
