#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

## usage: adr generate [REPORT [OPTION ...]]
##
## Generates summary documentation about the architecture decision records.

cmd=$1

if [ -z $cmd ]
then
    (cd "$adr_bin_dir" && find . -name '_adr_generate_*') | cut -c 17-
else
    "$adr_bin_dir/_adr_generate_$cmd" "${@:2}"
fi
