#!/bin/bash
set -e
source "$(dirname $0)/config.sh"

## usage: adr generate [REPORT [OPTION ...]]
##
## Generates summary documentation about the architecture decision records
## in Markdown format.
##
## The command `adr generate` lists the types of report.

cmd=$1

if [ -z $cmd ]
then
    (cd "$adr_bin_dir" && find . -name '_adr_generate_*' -perm +111) | cut -c 17-
else
    "$adr_bin_dir/_adr_generate_$cmd" "${@:2}"
fi
