#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

## usage: adr help [COMMAND]
##
## If COMMAND is given, displays help for that command. Otherwise lists
## the available commands.

cmd="$1"
cmdexe="$adr_bin_dir/adr-$cmd"

if [ -z "$cmd" -o ! -x $cmdexe ]
then
    echo "usage: $0 COMMAND [ARG] ..."
    echo "COMMAND is one of: "
    $adr_bin_dir/_adr_commands | sed 's/^/  /'
    echo "Run 'adr help COMMAND' for help on a specific command."
else
    grep -E '^##' "$cmdexe" | cut -c 4-
fi
