#!/bin/bash
set -e

template=$(dirname $0)/template.md
dstdir=$($(dirname $0)/_adr-dir)

title="$@"

if [ -z "$title" ]
then
    echo ERROR: no title given
    exit 1
fi

if [ -d $dstdir ]
then
    maxid=$(ls $dstdir | grep -Eo '^[0-9]+' | sort -rn | head -1)
    newnum=$(($maxid + 1))
else
    newnum=1
fi

newid=$(printf "%04d" $newnum)
slug=$(echo -n $title | tr -Ccs [:alnum:] - | tr [:upper:] [:lower:])
dstfile=$dstdir/$newid-$slug.md
date=${ADR_DATE:-$(date +%d/%m/%Y)}

mkdir -p $dstdir
cat $template | sed \
    -e "s|NUMBER|$newnum|" \
    -e "s|TITLE|$title|" \
    -e "s|DATE|$date|" \
    -e "s|STATUS|Accepted|" \
    > $dstfile

${VISUAL:-${EDITOR:-true}} $dstfile
echo $dstfile
